# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppCal.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(294, 436)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_Div = QtWidgets.QPushButton(Form)
        self.pushButton_Div.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Div.setFont(font)
        self.pushButton_Div.setStyleSheet("QPushButton {\n"
"  background-color: rgb(0, 196, 255);\n"
"  color: white; \n"
"  border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #5AD2FD, stop: 1 #5AD2FD);\n"
"}")
        self.pushButton_Div.setObjectName("pushButton_Div")
        self.gridLayout_2.addWidget(self.pushButton_Div, 1, 3, 1, 1)
        self.pushButton_Mult = QtWidgets.QPushButton(Form)
        self.pushButton_Mult.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Mult.setFont(font)
        self.pushButton_Mult.setStyleSheet("QPushButton {\n"
"  background-color: rgb(0, 196, 255);\n"
"  color: white; \n"
"  border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #5AD2FD, stop: 1 #5AD2FD);\n"
"}")
        self.pushButton_Mult.setObjectName("pushButton_Mult")
        self.gridLayout_2.addWidget(self.pushButton_Mult, 2, 3, 1, 1)
        self.pushButton_Num7 = QtWidgets.QPushButton(Form)
        self.pushButton_Num7.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num7.setFont(font)
        self.pushButton_Num7.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num7.setObjectName("pushButton_Num7")
        self.gridLayout_2.addWidget(self.pushButton_Num7, 2, 0, 1, 1)
        self.pushButton_Plus = QtWidgets.QPushButton(Form)
        self.pushButton_Plus.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Plus.setFont(font)
        self.pushButton_Plus.setStyleSheet("QPushButton {\n"
"  background-color: rgb(0, 196, 255);\n"
"  color: white; \n"
"  border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #5AD2FD, stop: 1 #5AD2FD);\n"
"}")
        self.pushButton_Plus.setObjectName("pushButton_Plus")
        self.gridLayout_2.addWidget(self.pushButton_Plus, 3, 3, 1, 1)
        self.pushButton_Moins = QtWidgets.QPushButton(Form)
        self.pushButton_Moins.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.pushButton_Moins.setFont(font)
        self.pushButton_Moins.setStyleSheet("QPushButton {\n"
"  background-color: rgb(0, 196, 255);\n"
"  color: white; \n"
"  border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #5AD2FD, stop: 1 #5AD2FD);\n"
"}")
        self.pushButton_Moins.setObjectName("pushButton_Moins")
        self.gridLayout_2.addWidget(self.pushButton_Moins, 4, 3, 1, 1)
        self.pushButton_Num9 = QtWidgets.QPushButton(Form)
        self.pushButton_Num9.setMinimumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num9.setFont(font)
        self.pushButton_Num9.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num9.setObjectName("pushButton_Num9")
        self.gridLayout_2.addWidget(self.pushButton_Num9, 2, 2, 1, 1)
        self.pushButton_Num1 = QtWidgets.QPushButton(Form)
        self.pushButton_Num1.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num1.setFont(font)
        self.pushButton_Num1.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num1.setObjectName("pushButton_Num1")
        self.gridLayout_2.addWidget(self.pushButton_Num1, 4, 0, 1, 1)
        self.pushButton_Egal = QtWidgets.QPushButton(Form)
        self.pushButton_Egal.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Egal.setFont(font)
        self.pushButton_Egal.setStyleSheet("QPushButton {\n"
"  background-color: rgb(0, 196, 255);\n"
"  color: white; \n"
"  border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #5AD2FD, stop: 1 #5AD2FD);\n"
"}")
        self.pushButton_Egal.setObjectName("pushButton_Egal")
        self.gridLayout_2.addWidget(self.pushButton_Egal, 5, 3, 1, 1)
        self.pushButton_Num5 = QtWidgets.QPushButton(Form)
        self.pushButton_Num5.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num5.setFont(font)
        self.pushButton_Num5.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num5.setObjectName("pushButton_Num5")
        self.gridLayout_2.addWidget(self.pushButton_Num5, 3, 1, 1, 1)
        self.pushButton_Num2 = QtWidgets.QPushButton(Form)
        self.pushButton_Num2.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num2.setFont(font)
        self.pushButton_Num2.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num2.setObjectName("pushButton_Num2")
        self.gridLayout_2.addWidget(self.pushButton_Num2, 4, 1, 1, 1)
        self.pushButton_Num3 = QtWidgets.QPushButton(Form)
        self.pushButton_Num3.setMinimumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num3.setFont(font)
        self.pushButton_Num3.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num3.setObjectName("pushButton_Num3")
        self.gridLayout_2.addWidget(self.pushButton_Num3, 4, 2, 1, 1)
        self.pushButton_Num8 = QtWidgets.QPushButton(Form)
        self.pushButton_Num8.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num8.setFont(font)
        self.pushButton_Num8.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num8.setObjectName("pushButton_Num8")
        self.gridLayout_2.addWidget(self.pushButton_Num8, 2, 1, 1, 1)
        self.pushButton_Module = QtWidgets.QPushButton(Form)
        self.pushButton_Module.setMinimumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Module.setFont(font)
        self.pushButton_Module.setStyleSheet("QPushButton {\n"
"  background-color: rgb(127,255,255);\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #C9FDFB, stop: 1 #80FFFC);\n"
"}")
        self.pushButton_Module.setObjectName("pushButton_Module")
        self.gridLayout_2.addWidget(self.pushButton_Module, 1, 2, 1, 1)
        self.pushButton_Num4 = QtWidgets.QPushButton(Form)
        self.pushButton_Num4.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num4.setFont(font)
        self.pushButton_Num4.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num4.setObjectName("pushButton_Num4")
        self.gridLayout_2.addWidget(self.pushButton_Num4, 3, 0, 1, 1)
        self.pushButton_Num6 = QtWidgets.QPushButton(Form)
        self.pushButton_Num6.setMinimumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num6.setFont(font)
        self.pushButton_Num6.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num6.setObjectName("pushButton_Num6")
        self.gridLayout_2.addWidget(self.pushButton_Num6, 3, 2, 1, 1)
        self.pushButton_Point = QtWidgets.QPushButton(Form)
        self.pushButton_Point.setMinimumSize(QtCore.QSize(70, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Point.setFont(font)
        self.pushButton_Point.setStyleSheet("QPushButton {\n"
"  background-color: rgb(127,255,255);\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #C9FDFB, stop: 1 #80FFFC);\n"
"}")
        self.pushButton_Point.setObjectName("pushButton_Point")
        self.gridLayout_2.addWidget(self.pushButton_Point, 5, 2, 1, 1)
        self.pushButto_C = QtWidgets.QPushButton(Form)
        self.pushButto_C.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButto_C.setFont(font)
        self.pushButto_C.setStyleSheet("QPushButton {\n"
"  background-color: rgb(127,255,255);\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #C9FDFB, stop: 1 #80FFFC);\n"
"}")
        self.pushButto_C.setObjectName("pushButto_C")
        self.gridLayout_2.addWidget(self.pushButto_C, 1, 0, 1, 1)
        self.pushButton_Num0 = QtWidgets.QPushButton(Form)
        self.pushButton_Num0.setMinimumSize(QtCore.QSize(142, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_Num0.setFont(font)
        self.pushButton_Num0.setStyleSheet("QPushButton {\n"
"   background-color: rgb(233, 255, 255);\n"
"   border: 1px solid gray;\n"
"   \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #BEBEBE​, stop: 1 #D7D7D7​);\n"
"}")
        self.pushButton_Num0.setObjectName("pushButton_Num0")
        self.gridLayout_2.addWidget(self.pushButton_Num0, 5, 0, 1, 2)
        self.pushButton_signal = QtWidgets.QPushButton(Form)
        self.pushButton_signal.setMinimumSize(QtCore.QSize(71, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        self.pushButton_signal.setFont(font)
        self.pushButton_signal.setStyleSheet("QPushButton {\n"
"  background-color: rgb(127,255,255);\n"
"  border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #C9FDFB, stop: 1 #80FFFC);\n"
"}")
        self.pushButton_signal.setObjectName("pushButton_signal")
        self.gridLayout_2.addWidget(self.pushButton_signal, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(291, 134))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    \n"
"  qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"  border: 1px solid gray;\n"
"    \n"
"    \n"
"\n"
"}")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_Div.setText(_translate("Form", "/"))
        self.pushButton_Mult.setText(_translate("Form", "X"))
        self.pushButton_Num7.setText(_translate("Form", "7"))
        self.pushButton_Plus.setText(_translate("Form", "+"))
        self.pushButton_Moins.setText(_translate("Form", "-"))
        self.pushButton_Num9.setText(_translate("Form", "9"))
        self.pushButton_Num1.setText(_translate("Form", "1"))
        self.pushButton_Egal.setText(_translate("Form", "="))
        self.pushButton_Num5.setText(_translate("Form", "5"))
        self.pushButton_Num2.setText(_translate("Form", "2"))
        self.pushButton_Num3.setText(_translate("Form", "3"))
        self.pushButton_Num8.setText(_translate("Form", "8"))
        self.pushButton_Module.setText(_translate("Form", "%"))
        self.pushButton_Num4.setText(_translate("Form", "4"))
        self.pushButton_Num6.setText(_translate("Form", "6"))
        self.pushButton_Point.setText(_translate("Form", "."))
        self.pushButto_C.setText(_translate("Form", "C"))
        self.pushButton_Num0.setText(_translate("Form", "0"))
        self.pushButton_signal.setText(_translate("Form", "+/-"))
        self.label.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
